### ISSUE TITLE
[BUG] "I don't care" are using wrong sequence in "Start" state

### ISSUE THREAD

**Issue by dounai2333** [cmooref17/Lethal-Company-TooManyEmotes#100]
When performing emote "I don't care", this emote are wrongly use the "Start" sequence from "Jubi slide".

**Comment by cmooref17** [comment]
Oh shoot, I noticed this myself earlier, but I thought I fixed this. Thanks! I will get this fixed soon.

**Comment by dounai2333** [comment]
Fixed in latest version.
