### ISSUE TITLE
nothing working after profile corruption

### ISSUE THREAD

**Issue by hsmtruman** [cmooref17/Lethal-Company-TooManyEmotes#101]
hi ! 

the other day while playing i had a bsod and restarted. when i came back to the game it told me that my profile got corrupted and to delete it so i did. now i cant see any emote ppl do and cant see the emote wheel when i push the keybind. i can see the keybind options and the config file in lethal config. i also get this error in the bepinex log when i start the game.

any help would be greatly appreciated ! 
![image_2024-04-02_024725304](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/1345130/293b91fa-b774-4183-9e8c-dfe7602ad689)

**Comment by cmooref17** [comment]
I'm assuming this is resolved now?
