### ISSUE TITLE
[BUG] Wontii letta me unmute/mute audio!!

### ISSUE THREAD

**Issue by Flloppis** [cmooref17/Lethal-Company-TooManyEmotes#103]
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/157853816/ec5d2f90-1e2f-4290-8f5a-59c7da62ba8b)
Tryin' too click Mute Emote Audio doesnt worksi anda only registers tha second emote slot!!

**Comment by cmooref17** [comment]
Does any of the emote menu work? And are there any errors in the console by chance?

**Comment by Flloppis** [comment]
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/157853816/ab633390-fa41-4e9b-a9d6-acc944c7886c)
Only tha button ta mute/unmute isnt workin' for me,
And whenna hoverin' over it- it caused itta highlight tha nearest emote!

**Comment by cmooref17** [comment]
Sorry, I missed this message. Do you use r2modman, and would you be able to share your profile with me with a code so I could test with your current mods? That's definitely not supposed to happen.

**Comment by Flloppis** [comment]
Ye! Ah usey r2modman! Thissa me profile codesi- 018ebd2c-8229-9247-f256-6c7c3ec6f1c6
