### ISSUE TITLE
Change a emote music ?

### ISSUE THREAD

**Issue by Jhonlate** [cmooref17/Lethal-Company-TooManyEmotes#105]
Hello, im not really familiar with modding, but i wanted to know if it was possible to change emotes music by myself, i would love to change boogie down music to funked up of Xxanteria, thanks in advance 
Far the best mod i had installed <3

**Comment by cmooref17** [comment]
Sorry, there is no way to do this currently, and I don't have plans for this, sorry! It would take extra time that I don't have a ton of haha
