### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Amelaks** [cmooref17/Lethal-Company-TooManyEmotes#106]
The mod doesn't work for me, it gives the following error in the console. I deleted all the mods, completely reinstalled Letnal Company, but nothing works.
Please tell me how to fix this? I think the problem is with file encryption, but I don't understand it. Sorry, I'm using Google translate.
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/139703617/2e5f2574-d224-4794-be54-33ad58e2a839)

**Comment by Lupylea** [comment]
I'm having the same issue, tried previous versions as well and launched it alone with only this mod active. I don't know what else I can try unless this needs to be manually added and isn't working on thunderstore??

**Comment by cmooref17** [comment]
Sorry, I missed this. It sounds like it might be a corrupt save file.

I would recommend deleting, or removeing/backing up the TooManyEmotes folder in your appdata to see if this fixes your issue.
AppData\LocalLow\ZeekerssRBLX\Lethal Company.

I can't remember if there even is a TooManyEmotes folder there.
If not, maybe try deleting your save files from this folder, and hopefully that fixes it?

Let me know if any of this solves this issue!

**Comment by Amelaks** [comment]
THANKS BRO сmooref17. I have been searching for so long how to solve this problem and you were the only ray of hope. If someone has the same problem, then to solve it you need to go to: AppData\LocalLow\ZeekerssRBLX. Next, I completely deleted the ZeekerssRBLX folder and everything worked for me!
