### ISSUE TITLE
[Error  : Unity Log] Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "PlayersContainer/Player/Misc/LineOfSightPivot/LineOfSightCubeSmall"

### ISSUE THREAD

**Issue by CoolLKKPS** [cmooref17/Lethal-Company-TooManyEmotes#108]
[Error  : Unity Log] Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "PlayersContainer/Player/Misc/LineOfSightPivot/LineOfSightCubeSmall"

when swing a stick? i don't know how to call that but that cause screen glitch though the map

**Comment by CoolLKKPS** [comment]
tbh idk, did i add scrap mods in my modpack? bc those scraps can link to toomanyemote

**Comment by cmooref17** [comment]
When you swing a stick? Are you referring to the baseball bat emote, maybe?

**Comment by CoolLKKPS** [comment]
uh.. it's just a wooden bat i think, ok at least i think.. it was a scrap when i found it

**Comment by CoolLKKPS** [comment]
btw those scraps is fun, but that could break the vanilla compatibility, so maybe u need to add a config option

**Comment by CoolLKKPS** [comment]
(*i actually try to use bat to hit my friends lol*)

**Comment by cmooref17** [comment]
It should be a config option already, but later today, this feature will be removed from this mod, and moved to a separate mod since it will prevent players from joining each other unless they both have the mod, or both do not have the mod, and I would like TooManyEmotes to continue to be compatible between all clients, whether some have it enabled, and some do not.

**Comment by CoolLKKPS** [comment]
cool!

**Comment by cmooref17** [comment]
Also, would you be able to share a video of this glitch you were having? You said something like it would cause the screen to glitch though the map?

It might be helpful.

**Comment by CoolLKKPS** [comment]
uh... will let u know if this issue happens again
