### ISSUE TITLE
[Issue/Suggestion] 3rd person cosmetic issue, and can u make zoom key rebindable?

### ISSUE THREAD

**Issue by CoolLKKPS** [cmooref17/Lethal-Company-TooManyEmotes#111]
https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/96377775/8c36f00c-7c22-4d3f-8091-a4bf242fa983

**Comment by CoolLKKPS** [comment]
he use my cosmetic in 3rd person view

**Comment by cmooref17** [comment]
This seems to be a bug currently when other players have no cosmetics on. Not sure why, but I will look at this in the future.

**Comment by cmooref17** [comment]
Actually, I lied. Apparently you can bind scroll up/down through InputUtils. I don't think you could have in the past, but seems like you can now. I should be able to add the keybinds for this in the keybind menu sometime.

**Comment by CoolLKKPS** [comment]
ah ok, anyway thx for the reply, still working on my modpack now

**Comment by CoolLKKPS** [comment]
zoom key now rebindable!
im not sure cosmetic issue, so link issue here: https://github.com/notnotnotswipez/MoreCompany/issues/73

**Comment by CoolLKKPS** [comment]
should be fixed?
