### ISSUE TITLE
Issue with mime emote

### ISSUE THREAD

**Issue by Kichip** [cmooref17/Lethal-Company-TooManyEmotes#112]
The mime emote will make all other emotes silent

**Comment by cmooref17** [comment]
Only the mime emote?

**Comment by Kichip** [comment]
Yeah, only the mime emote from what i know. It sometimes fixes when you get
back into the ship, sometimes it doesnt

**Comment by cmooref17** [comment]
It seems weird why it would be just the mime emote. The mime emote is not a unique emote, in the sense that it does special things. It is an emote with animation, and does not loop. It also does not have any sound. There are quite a few emotes that have these exact characteristics. For instance, most of the complementary emotes have these exact same qualities, like dust off hands. Could you check to see if dust off hands breaks, and then check again sometime if the mime emote still breaks?

Also, I did test mime time, but it seems fine for me. Performing emotes after that still had sound.

Might be helpful, but do you play music through the boomboxes, or did you disable that?

**Comment by Kichip** [comment]
I disabled the boomboxes thing, but maybe it’s not an issue with the mime,
but rather with conflicting emotes? Maybe theres an issue where sound will
break when swapping between emotes or when in a server using different
emotes. It could be a lot of things, but the core issue is just the music
breaking entirely. Also it only happened to two people in the server,
despite others using same/similar emotes

**Comment by cmooref17** [comment]
I just wanted to check to see if this is still happening? I haven't specifically fixed anything about this, but maybe it randomly stopped happening? If it's still happening, let me know and I can look into this again soon.
