### ISSUE TITLE
[Suggestion] Refine interaction with Disco Ball

### ISSUE THREAD

**Issue by DLumi** [cmooref17/Lethal-Company-TooManyEmotes#113]
Currently Disco Ball music will go over any song player by emote, which does not sound too good.
I propose a few variants to resolve this interaction:
1) Remove Disco Ball music entirely
2) Override Disco Ball music with the emote song (the music will not resume automatically)
3) Pause Disco Ball music when emoting, resume when emote ends

Optionally, this behavior could be added to the config. 

IMO, the best option would be no. 3 but I have no idea how hard would it be to implement.

**Comment by cmooref17** [comment]
I haven't played on v50 yet, tbh, aside from testing, but is the disco ball a new item? A modded item?

**Comment by DLumi** [comment]
> I haven't played on v50 yet, tbh, aside from testing, but is the disco ball a new item? A modded item?

New shop item, provides good visual effects as well as some music. However, as I mentioned, it clashed with this mod's music

**Comment by cmooref17** [comment]
Ah, you're right. I loaded it up a bit ago and saw what you meant. I just added a patch for this, and will include it in the next update, thanks!
