### ISSUE TITLE
player skins issue

### ISSUE THREAD

**Issue by TheComicRelief** [cmooref17/Lethal-Company-TooManyEmotes#115]
the latest update broke the player skin still showing them in 1st person
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/167217146/4b7e38c1-87cd-438a-aea8-7797d34e59de)
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/167217146/804cda66-5257-4b04-8691-d2146473bfd9)

**Comment by cmooref17** [comment]
Yes, this should be fixed in 2.1.8. if you can confirm that it is not fixed in this version, please create another issue but for now, I will close this one. Thanks!
