### ISSUE TITLE
"Always Emote On First Encounter"Setting Not work

### ISSUE THREAD

**Issue by cangming99** [cmooref17/Lethal-Company-TooManyEmotes#116]
I found that even when the ‘Always Emote On First Encounter’ setting is set to False, the first MaskedEnemy encountered will definitely perform an emote.
Here are my configuration settings:
![1713597010727](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/85931842/9ecc4734-5334-414d-93a0-b90915e96762)

**Comment by cmooref17** [comment]
Huh, I can take a look at this soon. It's likely my logic is not quite correct, or maybe I forgot to reference that config option? We will see, but thanks!

**Comment by cmooref17** [comment]
Btw, I just checked on this, and it seems like I'm not even referencing that config in my logic. Thanks for letting me know! I'll get this fix added to the next update!
