### ISSUE TITLE
bug when using versions 2.1.5 through 2.1.8 of this mod with version 49 of lethal company

### ISSUE THREAD

**Issue by Kai-Schlabitz** [cmooref17/Lethal-Company-TooManyEmotes#117]
When in the ship, I cannot move or store furniture like the filing cabinet. Strangely enough, rotation works. The suit rack is also empty. Even the default suit is missing.

I tested with only this mod and BepInExPack installed.

Thank you for your work and time.

**Comment by Kai-Schlabitz** [comment]
I forgot to mention that the config is default and that it doesn't seem to be a problem on version 50 of lethal company.

**Comment by cmooref17** [comment]
Do you have any errors in your console? That would be the first things to check, and thanks if you can share them!

**Comment by Kai-Schlabitz** [comment]
Here is a video of what happens and the console logs:

https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/80277456/553258c5-35c4-4a61-ad99-d2adf5d637b1

[Message:   BepInEx] BepInEx 5.4.21.0 - Lethal Company (12/19/2023 4:40:55 PM)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [TooManyEmotes 2.1.8]
[Info   :TooManyEmotes-2.1.8] BindingConfigs
[Info   :TooManyEmotes-2.1.8] Initializing custom emote hotkeys.
[Info   :TooManyEmotes-2.1.8] Successfully loaded 26 animation clips from asset bundle: Assets/emotes_complementary
[Info   :TooManyEmotes-2.1.8] Successfully loaded 83 animation clips from asset bundle: Assets/emotes_0
[Info   :TooManyEmotes-2.1.8] Successfully loaded 117 animation clips from asset bundle: Assets/emotes_1
[Info   :TooManyEmotes-2.1.8] Successfully loaded 79 animation clips from asset bundle: Assets/emotes_2
[Info   :TooManyEmotes-2.1.8] Successfully loaded 7 animation clips from asset bundle: Assets/emotes_3
[Info   :TooManyEmotes-2.1.8] Successfully loaded 4 animation clips from asset bundle: Assets/emotes_special
[Info   :TooManyEmotes-2.1.8] Successfully loaded radial menu asset.
[Info   :TooManyEmotes-2.1.8] Loaded 18 emote props.
[Info   :TooManyEmotes-2.1.8] Loading 132 dmca-free audio clips.
[Info   :TooManyEmotes-2.1.8] Loading 117 dmca audio clips.
[Info   :TooManyEmotes-2.1.8] TooManyEmotes finished loading!
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] dxgi: swapchain SetFullscreenState failed (887a0022).
[Warning: Unity Log] Failed to change display to ExclusiveFullscreen...reverting to FullscreenWindow
[Info   : Unity Log] Saving changed settings
[Info   : Unity Log] subcribing to steam callbacks
Setting breakpad minidump AppID = 1966720
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198080332186 [API loaded no]
[Info   : Unity Log] Returning week num: 18
[Info   : Unity Log] week num: 18
[Info   : Unity Log] host button pressed
[Info   : Unity Log] Returning week num: 18
[Info   : Unity Log] AAAAAA
[Info   : Unity Log] 2
[Info   : Unity Log] 0
[Info   : Unity Log] AAAAAA
[Info   : Unity Log] 2
[Info   : Unity Log] 1
[Info   : Unity Log] AAAAAA
[Info   : Unity Log] 2
[Info   : Unity Log] 2
[Info   : Unity Log] AAAAAA
[Info   : Unity Log] 2
[Info   : Unity Log] -1
[Info   : Unity Log] Returning week num: 18
[Info   : Unity Log] host button pressed
[Info   : Unity Log] Displaying menu message
[Info   : Unity Log] Connection approval callback! Game version of client request:
[Info   : Unity Log] Joining client id: 0; Local/host client id: 0
[Info   : Unity Log] Stopped connection approval callback, as the client in question was the host!
[Warning: Unity Log] [Netcode] You cannot decline the host connection. The connection was automatically approved.
[Info   : Unity Log] started host!
[Info   : Unity Log] are we in a server?: True
[Info   : Unity Log] Lobby has been created
[Info   :TooManyEmotes-2.1.8] Loading AudioManager preferences.
[Info   : Unity Log] Enabling connection callbacks in StartOfRound
[Info   : Unity Log] Began listening to SceneManager_OnLoadComplete1 on this client
[Info   :TooManyEmotes-2.1.8] Initializing emote menu
[Info   :TooManyEmotes-2.1.8] Loading AudioManager preferences.
[Info   :TooManyEmotes-2.1.8] Loading ThirdPersonEmoteController preferences.
[Info   :TooManyEmotes-2.1.8] Initializing animation renderer
[Error  : Unity Log] MissingFieldException: Field not found: UnityEngine.AudioSource .CozyLights.turnOnAudio Due to: Could not find field in class
Stack trace:
(wrapper dynamic-method) AutoParentToShip.DMD<AutoParentToShip::Awake>(AutoParentToShip)

[Error  : Unity Log] MissingFieldException: Field not found: UnityEngine.AudioSource .CozyLights.turnOnAudio Due to: Could not find field in class
Stack trace:
(wrapper dynamic-method) AutoParentToShip.DMD<AutoParentToShip::Awake>(AutoParentToShip)

[Error  : Unity Log] MissingFieldException: Field not found: UnityEngine.AudioSource .CozyLights.turnOnAudio Due to: Could not find field in class
Stack trace:
(wrapper dynamic-method) AutoParentToShip.DMD<AutoParentToShip::Awake>(AutoParentToShip)

[Error  : Unity Log] MissingFieldException: Field not found: UnityEngine.AudioSource .CozyLights.turnOnAudio Due to: Could not find field in class
Stack trace:
(wrapper dynamic-method) AutoParentToShip.DMD<AutoParentToShip::Awake>(AutoParentToShip)

[Error  : Unity Log] MissingFieldException: Field not found: UnityEngine.AudioSource .CozyLights.turnOnAudio Due to: Could not find field in class
Stack trace:
(wrapper dynamic-method) AutoParentToShip.DMD<AutoParentToShip::Awake>(AutoParentToShip)

[Warning: Unity Log] damageTrigger is disabled! Netcode for GameObjects does not support spawning disabled NetworkBehaviours! The InteractTrigger component was skipped during spawn!
[Info   : Unity Log] level id: 0
[Info   : Unity Log] Changing level
[Info   : Unity Log] Item sales percentages #0: 0
[Info   : Unity Log] Item sales percentages #1: 0
[Info   : Unity Log] Item sales percentages #2: 0
[Info   : Unity Log] Item sales percentages #3: 0
[Info   : Unity Log] Item sales percentages #4: 0
[Info   : Unity Log] Item sales percentages #5: 0
[Info   : Unity Log] Item sales percentages #6: 0
[Info   : Unity Log] Item sales percentages #7: 0
[Info   : Unity Log] Item sales percentages #8: 0
[Info   : Unity Log] Item sales percentages #9: 0
[Info   : Unity Log] Item sales percentages #10: 0
[Info   : Unity Log] Item sales percentages #11: 0
[Info   : Unity Log] Item sales percentages #12: 0
[Error  : Unity Log] MissingFieldException: Field not found: UnityEngine.AudioSource .CozyLights.turnOnAudio Due to: Could not find field in class
Stack trace:
(wrapper dynamic-method) AutoParentToShip.DMD<AutoParentToShip::Awake>(AutoParentToShip)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion, Transform)
StartOfRound:SpawnUnlockable(Int32)
StartOfRound:DMD<StartOfRound::LoadUnlockables>(StartOfRound)
StartOfRound:DMD<StartOfRound::Start>(StartOfRound)

[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Info   : Unity Log] Suits: 1
[Info   : Unity Log] Suit #0: 0
[Info   : Unity Log] pos: (-2.45, 2.75, -8.41); rot: (0.00, 90.00, 0.00)
[Info   :TooManyEmotes-2.1.8] Loading game values.
[Info   :TooManyEmotes-2.1.8] Resetting unlocked emotes.
[Info   :TooManyEmotes-2.1.8] Loaded Seed: 0
[Info   : Unity Log] Key 'shipGrabbableItems' does not exist
[Info   :TooManyEmotes-2.1.8] Rotating emote selection in store. Seed: 498396338
[Info   : Unity Log] Item sales percentages #0: 0
[Info   : Unity Log] Item sales percentages #1: 0
[Info   : Unity Log] Item sales percentages #2: 0
[Info   : Unity Log] Item sales percentages #3: 0
[Info   : Unity Log] Item sales percentages #4: 0
[Info   : Unity Log] Item sales percentages #5: 0
[Info   : Unity Log] Item sales percentages #6: 0
[Info   : Unity Log] Item sales percentages #7: 0
[Info   : Unity Log] Item sales percentages #8: 0
[Info   : Unity Log] Item sales percentages #9: 0
[Info   : Unity Log] Item sales percentages #10: 0
[Info   : Unity Log] Item sales percentages #11: 0
[Info   : Unity Log] Item sales percentages #12: 0
[Info   : Unity Log] Group credits: 60
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/LightSwitchContainer/PlacementCollider"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/Cube"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/AnimatedShipDoor/HangarDoorLeft (1)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (1)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ControlDesk.001"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (3)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (7)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/StorageCloset/Cube.000/Cube"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (6)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (8)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (5)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (4)"
[Info   : Unity Log] Taking control of player Player and enabling camera!
[Info   : Unity Log] Starting voice tracking for player: SecurityGoat
[Info   :TooManyEmotes-2.1.8] Loading ThirdPersonEmoteController preferences.
[Info   :TooManyEmotes-2.1.8] Initializing local player.
[Info   : Unity Log] !!!! ENABLING CAMERA FOR PLAYER: Player
[Info   : Unity Log] !!!! connectedPlayersAmount: 0
[Info   :TooManyEmotes-2.1.8] Rotating emote selection in store. Seed: 498396338
[Info   : Unity Log] Has beta?: {hasBeta}
[Info   : Unity Log] Has beta save data: True
[Warning: Unity Log] [Dissonance:Recording] (17:40:28.105) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.7840922)
[Info   : Unity Log] Saving placed position as: (7.13, 1.10, -11.64)
[Info   : Unity Log] Saving placed position as: (6.42, 1.10, -14.35)
[Info   : Unity Log] Saving placed position as: (5.51, 1.10, -14.16)
[Warning: Unity Log] PlayOneShot was called with a null AudioClip.
[Info   : Unity Log] DISABLE OBJECT C
[Info   : Unity Log] DISABLE OBJECT D
[Info   : Unity Log] Saving placed position as: (6.33, 2.04, -13.92)
[Warning: Unity Log] PlayOneShot was called with a null AudioClip.
[Info   : Unity Log] DISABLE OBJECT C
[Info   : Unity Log] DISABLE OBJECT D
[Info   : Unity Log] Set interminalmenu to true: True
[Error  : Unity Log] Trying to add Caret (TMPro.TMP_SelectionCaret) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
[Info   : Unity Log] Parsed word: file
[Info   : Unity Log] Could not parse word: c
[Info   : Unity Log] noun keyword: file cabinet ; verb keyword: buy ; result null? : False
[Info   : Unity Log] result: FileCabinet1
[Info   : Unity Log] Is unlockable 'File Cabinet in storage?: True
[Info   : Unity Log] Moving object out of storage 1
[Info   : Unity Log] Moving object out of storage 2
[Info   : Unity Log] PLAYER OPENED MENU
[Info   : Unity Log] In terminal menu: False
[Info   : Unity Log] PLAYER OPENED MENU
[Info   : Unity Log] In terminal menu: False
[Info   : Unity Log] PLAYER OPENED MENU
[Info   : Unity Log] In terminal menu: False
[Info   : Unity Log] PLAYER OPENED MENU
[Info   : Unity Log] In terminal menu: True
[Info   : Unity Log] Calling stop animation function StopUsing server rpc for player: 0
[Info   : Unity Log] STOPPING SPECIAL ANIMATION ON LOCAL CLIENT; player who was using: SecurityGoat
[Info   : Unity Log] Quit terminal; inTerminalMenu true?: {playerScript.inTerminalMenu}
[Info   : Unity Log] Saving placed position as: (3.20, 1.10, -14.35)
[Info   : Unity Log] Saving placed position as: (4.23, 1.10, -14.34)
[Warning: Unity Log] [Dissonance:Recording] (17:41:13.587) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.1652844)
[Warning: Unity Log] [Dissonance:Recording] (17:41:38.501) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.2849927)
[Warning: Unity Log] [Dissonance:Recording] (17:41:41.523) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.4527077)
[Warning: Unity Log] [Dissonance:Recording] (17:41:43.745) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.4023033)
[Warning: Unity Log] [Dissonance:Recording] (17:41:46.752) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.3855965)
[Warning: Unity Log] [Dissonance:Recording] (17:41:47.508) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.1507804)
[Warning: Unity Log] [Dissonance:Recording] (17:41:48.984) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.2178299)
[Warning: Unity Log] [Dissonance:Recording] (17:41:50.513) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.2678466)
[Warning: Unity Log] [Dissonance:Recording] (17:41:59.504) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.6364448)
[Warning: Unity Log] [Dissonance:Recording] (17:42:08.530) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.1864813)

**Comment by cmooref17** [comment]
Oh, that would cause issues with v49. That was related to the Disco patcher, but that was not present until v50. If I update this mod today, I may be able to change this slightly so it works for both versions. Hopefully that is the case, but I will update this issue if I can get it working

**Comment by cmooref17** [comment]
Sorry, I forgot to update this issue. This should be fixed as of the last update. If you continue to run into issues, please create another issue, thanks!
