### ISSUE TITLE
Emote dial won't open following update to v2.1.10 [Game crashed during Disco Party]

### ISSUE THREAD

**Issue by Azure0219** [cmooref17/Lethal-Company-TooManyEmotes#119]
Hi there. Running into a weird issue that I can't fix by reinstalling the mod or game. I tried a fresh install of lc with only bepin, TooManyEmotes and InputUtils installed but for some reason **I cannot open the radial menu in-game**. Even with a different keybinding it's like the mod doesn't exist in-game because the "emotes" option isn't available in the terminal. Party members can see the dial if I host, but they can't use the emotes until they sync with me, which I'm sure why its not happening. 

When it broke, the disco ball was active (lights were off in the ship), and we had a few of us syncing with an emote and my game crashed. Ever since then, I cannot get the mod to work. Any ideas? 

Game version: v50
Mod Version: v2.1.10
BepInExPack v5.4.2100
InputUtils v0.7.4

One thing I will add, it was working on v2.1.9. We were playing for a couple of hours with that version but after the game crashed and my computer had to be rebooted, I noticed the update to v2.1.10 was available. I updated my modlist and had my friends do the same. After that, it was broken. I tried downgrading to v2.1.9 and the radial dial still doesn't work. :(

**Comment by Azure0219** [comment]
Just ran the same setup on a separate computer. Getting this error message when TooManyEmotes is loading only on my PC. 

[Error  : Unity Log] CryptographicException: Could not decrypt file. Please ensure that you are using the same password used to encrypt the file.
Stack trace:
ES3Internal.ES3Stream.CreateStream (ES3Settings settings, ES3Internal.ES3FileMode fileMode) (at <9a53cee95b8c4093a7e8ca243c325c34>:0)
ES3Reader.Create (ES3Settings settings) (at <9a53cee95b8c4093a7e8ca243c325c34>:0)
ES3.KeyExists (System.String key, ES3Settings settings) (at <9a53cee95b8c4093a7e8ca243c325c34>:0)
ES3.KeyExists (System.String key) (at <9a53cee95b8c4093a7e8ca243c325c34>:0)
TooManyEmotes.SaveManager.LoadFavoritedEmotes () (at <eceaf6c927e44feea1c5e8d39181d84d>:0)
TooManyEmotes.EmotesManager.BuildEmotesList () (at <eceaf6c927e44feea1c5e8d39181d84d>:0)
TooManyEmotes.Plugin.Awake () (at <eceaf6c927e44feea1c5e8d39181d84d>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by cmooref17** [comment]
Sorry about that, but it does sound like a corrupted file. I still need to figure out why this is happening, and have my script try to fix itself when this happens. For now, you might be able to see the toomanyemotes file at this directory. AppData/LocalLow/ZeekersSomething/LethalCompany.

The path should be relatively close to that lol, but you should see a TooManyEmotes file here, and you should try deleting it and see if that fixes your issue.

Hopefully in the future, I can have this automatically fix itself when things like this happen.

**Comment by Azure0219** [comment]
There was indeed a TooManyEmotes_LocalSaveData file in the AppData>LocalLow>ZeekerssRRBLX>Lethal Company directory. I tried deleting it and unfortunately no change. However there was also a SaveFile.es3 here that I didn't recognize and turns out that was the corrupt file. Deleted it and the mod created a new one on the next run. The dial works again!
