### ISSUE TITLE
"Toggle Rotate Character In Emote"Setting Not work

### ISSUE THREAD

**Issue by cangming99** [cmooref17/Lethal-Company-TooManyEmotes#121]
No matter how I set the “Toggle Rotate Character in Emote”, I have to hold down ALT to rotate the character.

**Comment by cmooref17** [comment]
Oh, thank you for bringing this up. This was on my list to do for one of my recent updates, but I ended up forgetting about it. I'll try to get this added back in soon. Thanks!

**Comment by cmooref17** [comment]
Okay, so I feel like I remember this not working for me earlier, but it's working for me now, for whatever reason.
When you set this option to toggle in the config, does the control tips on the top right say "hold" or "toggle"?

**Comment by cangming99** [comment]
The tips is "toggle".When I press Alt once, I can rotate the character, but when I press it again, it doesn’t work, which is different from the previous logic.

**Comment by cmooref17** [comment]
I still couldn't replicate your specific issue, but I did run into another issue that could be related. I fixed this and updated the mod to 2.1.12.

Could you test this version and let me know if your issue is fixed?

**Comment by cangming99** [comment]
https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/85931842/ffd79eae-2cb9-4fe6-8366-970554a672f1

In the video, I pressed ALT instead of holding it down, maybe this is normal? It’s just different from before, as I used to be able to rotate the character in the emote directly without pressing ALT.

**Comment by cmooref17** [comment]
What should happen, is when you emote, you can move and turn. If you press and release alt once, it will not let you turn your character anymore. If you press and release alt again, it should let you turn your character again.

Is this not what's happening in the video?

**Comment by cangming99** [comment]
Sorry, I misunderstood before, but now I understand now
