### ISSUE TITLE
Can't do/see any emote

### ISSUE THREAD

**Issue by thetyta** [cmooref17/Lethal-Company-TooManyEmotes#122]
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/162638906/e2522857-e881-4df3-afe8-4386e68b8c87)

When I join the Lobby, I can't use or see any emotes that others do, and then this screen pops up, even when I deleted other mods and tried it by itself.

**Comment by cmooref17** [comment]
You most likely got an error in your console/logs. Maybe a mod conflicting? WOuld you be able to share it if you can find that error?

**Comment by thetyta** [comment]
> You most likely got an error in your console/logs. Maybe a mod conflicting? WOuld you be able to share it if you can find that error?

As I stated before, even with only this mod, the bug remains and no error pops up on console
Also, I can't close this screen or move my character

https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/162638906/9762ce63-3373-4878-b67e-c68946443e69

![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/162638906/7b55926e-4ef1-424c-b272-95d890c4ded0)

and this shows every milisecond

**Comment by cmooref17** [comment]
Sorry, I see where you said that you tried this with only this mod enabled. It seems like there's definitely an error in the logs. The error should be right before all that spam I'm guessing, so if it is possible you can get that, that would be very helpful. It is very strange that you would be getting this error with only this mod installed. What version of the game are you on? V49? V50?

**Comment by cmooref17** [comment]
Okay, good to know! I'll see if I can prevent this error as well, just in case it is causing other issues.

**Comment by cmooref17** [comment]
I updated the mod to 2.1.12, and this version should automatically fix this bug. The bug is related to some form of file corruption, I believe. If this still doesn't solve your issue, let me know, and I can show you how to delete the corrupted file.

**Comment by thetyta** [comment]
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/162638906/a96e4fb5-96b3-4985-b298-4cc1967720f5)
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/162638906/4e651121-e304-4368-ae7f-e9e3f181039a)

even updating the mod hasn't fixed the issue

**Comment by MrNuckMAn** [comment]
> I updated the mod to 2.1.12, and this version should automatically fix this bug. The bug is related to some form of file corruption, I believe. If this still doesn't solve your issue, let me know, and I can show you how to delete the corrupted file.

Hello! I'm having this same issue as well. If you say it's a corrupted file, may you help me delete it?
Thanks in advance!

**Comment by cmooref17** [comment]
Ah, sorry about that.

I would head to this directory:
C:\Users\YOUR_USER\AppData\LocalLow\ZeekerssRBLX\Lethal Company

And delete this file: SaveFile.es3

Don't delete the TooManyEmotes file. That one isn't causing the issue.

Also, to help me test this issue, and figure out why this is happening, would you be able to send me this file? Maybe attach it here, or if you would rather email it to me, email it to me at cmooref17@gmail.com.

But if deleting this file doesn't fix the issue, you could try deleting "LCGeneralSaveData".

I will update this mod again soon to fix the error you received. I'm really not sure why the error is still appearing, but this time, it's related to deleting a key instead of checking if a key exists.

**Comment by thetyta** [comment]
Deleting the file fixed the issue! thank you so much!

I will send it to your email since github don't support the file type

**Comment by MrNuckMAn** [comment]
It fixed removing the file, thank you s much!

**Comment by cmooref17** [comment]
Okay, I'm glad to hear it! And thanks to you both. I received your save files, so hopefully I can do some testing to see if I can find a better solution for this error. I will close this issue for now.

I will also push out an update soon with more automatic fixes which might fix this more recent error you shared.
