### ISSUE TITLE
Mod glitches out UI and becomes unusable

### ISSUE THREAD

**Issue by DoubleG17** [cmooref17/Lethal-Company-TooManyEmotes#123]
Mod was working fine for me yesterday but when I booted the game up today it was glitching out. I use the reserved slot mods for flashlight and walkie-talkie and the HUD was all messed up. I am also unable to highlight/activate any of the emotes through the emote wheel. Other HUD features like the little progress bar that shows up when pulling the ship lever or opening doors is also gone/invisible with the emote mod activated. I verified my game files and tried toomanyemotes on a completely fresh modlist (just toomanyemotes and bepinex pack installed) and the issues still persisted. I've attached a screenshot of what it looks like when I load into a game. See how the UI is messed up. Really sucks because this mod brings me and my friends a lot of joy. 
![Screenshot 2024-04-28 142940](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/130624847/a3d24234-6752-46c1-9c2d-21bddb775f3e)

**Comment by cmooref17** [comment]
Seeing this usually means there was an error in the console/logs. If you could share the logs, or at least the error that might have appeared, I could see why this is happening. Thanks!

**Comment by DoubleG17** [comment]
[LogOutput.log](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/files/15144004/LogOutput.log)
I've attached my log output. Sorry, I should've done that before.

**Comment by cmooref17** [comment]
Okay, I'll check this out when I get home, thanks!

**Comment by cmooref17** [comment]
Btw, I found the issue and am pushing the fix out now. There was a section of code that was loading preferences from a file, but from an old location, and I forgot to check and apply fixes in case of file corruption.

If you still run into issues after 2.1.14, please create another issue! But for now, I will close this one.
