### ISSUE TITLE
[Issue] v2.1.15, won't adjust the view while emoting in firstperson, cannot check/uncheck "mute emote audio" option in emote wheel

### ISSUE THREAD

**Issue by CoolLKKPS** [cmooref17/Lethal-Company-TooManyEmotes#126]
same as topic

**Comment by CoolLKKPS** [comment]
maybe i need to provide my screen resolution, very standard 1080p 16:9; and in previous version first person emote works great, but won't adjust the view after recently update, so i may won't track this issue, instead, if u need i will provide my modpack here to let u investigate

**Comment by cmooref17** [comment]
What do you mean by adjust view? Like you can't rotate the camera while emoting in third person?

Also does the mute checkbox not work at any time? Or only while emoting? Only while emoting in first person?

**Comment by cmooref17** [comment]
Okay, I think I found the issue with the UI, and not being able to hover over certain elements. I will include this in the next update!

**Comment by CoolLKKPS** [comment]
won't move the player view camera while emoting in first person
in my case, when i try to click mute box, will result to perform another emote, and i guess emote hitbox are bigger than mute hitbox

**Comment by cmooref17** [comment]
This is normal, by the way. I want to add functionality to allowing the player to move the camera, but I'll have to do it when I have more time to implement a proper solution. I will keep it on my todo list!

**Comment by CoolLKKPS** [comment]
ok, but i sug if performing emote with first person, player can move the camera, but also will rotating the emote direction, and the player view camera will following the player's head position (even performing some emotes is really painful if enable first person)

**Comment by cmooref17** [comment]
I did re-enable the camera to follow the player's head during first person emotes. I previously disabled it temporarily, but I forgot why. This was enabled again in the recent update.

And I will add a proper method eventually for allowing you to move the camera a little during first person emotes. I just don't know when I'll have the time to do it yet.

**Comment by CoolLKKPS** [comment]
@cmooref17 uh and i did found some issues about first person and emote while moving features in previous version
1. only when `emote while moving` enabled, bee suit and bunny suit ear cosmetic (Not MoreCompany cosmetic) will not correctly stick on the player's head
2. u did add a feature in recently update, when u press rotation key and moving, u can stop emoting while in first person; but idk, first if im moving without `emote while moving` enabled, emote should stop no matter what keybind are press; and always enable rotation when in first person bc lock rotation in first person is pointless; ONLY allow lock rotation in third person emoting, and won't lock rotation while emoting by default
3. if enable `emote while moving`, the cam always should not follow the player's head, just a remind

**Comment by CoolLKKPS** [comment]
those are my previous feedback but i forgot send those feedback to u, uh yea... some part are modified bc u already found a better solution

**Comment by CoolLKKPS** [comment]
> ok, but i sug if performing emote with first person, player can move the camera, but also will rotating the emote direction, and the player view camera will following the player's head position (even performing some emotes is really painful if enable first person)

and don't confuse, this only for first person, again if enable `emote while moving`, the cam always should not follow the player's head, will cause some problem otherwise

**Comment by CoolLKKPS** [comment]
btw uh can u do me a favor? i like to send issue to `Immersive Visor` author but i can't find his github, that mod got a error when hosting a game and other client are joining

[Error : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Transform.get_position () (at <e27997765c1848b09d8073e5d642717a>:0)
ManualCameraRenderer.Update () (at <255c0877f9414c3aa6f1fe5079ac13f3>:0)

**Comment by cmooref17** [comment]
First off, yes, if you emote in first person, but allow moving while emoting, the camera will not follow the player's head.

Also, what is the favor that you're asking exactly?

**Comment by CoolLKKPS** [comment]
uh actually, i already send the issue in there, about Immersive_Visor custom visor rim to disappear, it was conflict issue
https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/issues/104

**Comment by CoolLKKPS** [comment]
i was think about send conflict issue directly to Immersive_Visor before, but i can't find Immersive_Visor author github, that's why i need someone who can use discord to send issue to Immersive_Visor author

**Comment by CoolLKKPS** [comment]
and always, really appreciate for ur reply
