### ISSUE TITLE
[Log Conflict] with LogNeuter, cause issue that will made no changes to method: GameNetcodeStuff.PlayerControllerB|ItemSecondaryUse_performed

### ISSUE THREAD

**Issue by CoolLKKPS** [cmooref17/Lethal-Company-TooManyEmotes#128]
so in vanilla game, u will see some trash logs similar like:
secondary use A
secondary use B
secondary use C
secondary use D
secondary use E
secondary use F
secondary use G

and if u install LogNeuter, u can see this is from `[GameNetcodeStuff.PlayerControllerB|ItemSecondaryUse_performed]`, but this mod will cause LogNeuter to made no changes to that method, this is a big conflict and will stop people diagnosing by seeing logs

**Comment by CoolLKKPS** [comment]
if u don't know what can cause that, here the config

**Comment by CoolLKKPS** [comment]
[BlueAmulet.LogNeuter.zip](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/files/15290568/BlueAmulet.LogNeuter.zip)

**Comment by cmooref17** [comment]
Sorry for the late reply. I'm not sure why this mod would do that. I can look into this later, though. Thanks for letting me know!

**Comment by cmooref17** [comment]
Maybe I'm confused what you're trying to say. What changes does LogNeuter make to this method that my mod is blocking?
I thought you were trying to say those logs don't appear anymore when TooManyEmotes is enabled.

**Comment by CoolLKKPS** [comment]
what i trying to do is block spamming logs, bc that hindering me from investigating the issues, idk why logneuter refuse to block that method, but that did cause some spamming logs appear again, so i like to know why
