### ISSUE TITLE
Where is the config, and how can i change it? (Manual Install)

### ISSUE THREAD

**Issue by liron-kruchinin** [cmooref17/Lethal-Company-TooManyEmotes#13]
Hey, im trying to figure out where is the config for the mod and how to change it, could you give me a hint for that?
Thanks :D

**Comment by cmooref17** [comment]
Do you use a mod manager, such as r2modman? If so, if you're in your profile, you can click on Config editor on the left, and find it there.

If you don't use a mod manager, you can find where you put your bepinex folder (which might be in your game's root folder). The config path here would probably be something like steam/steamapps/common/LethalCompany/BepInEx/config. The path might not be that exactly, but I would at least look for the BepInEx folder in your LethalCompany game folder.

Hope this helps!
