### ISSUE TITLE
Some Config Settings dont work

### ISSUE THREAD

**Issue by MyUserNameIsVeryBad** [cmooref17/Lethal-Company-TooManyEmotes#135]
Changing The RotationWeight Options Or the EmotesInStoreRotation in the config Doesnt affect anything even after Restarts

**Comment by cmooref17** [comment]
I'll have to check on this this weekend.
Also, you don't have global emote unlocks enabled, do you? I can't remember the exact name of that config, but that might prevent changing that.

**Comment by MyUserNameIsVeryBad** [comment]
I actually do have it enabled
