### ISSUE TITLE
Default and Custom suits, are transparent on 2.1.20  with more company cosmetics installed

### ISSUE THREAD

**Issue by Gonzas2000** [cmooref17/Lethal-Company-TooManyEmotes#137]
I can only see the cosmetics from more company and the shoulder part of the suit with the new version, previous 2.1.19 works just fine

**Comment by cmooref17** [comment]
Would you mind sending me a mod list? I wonder if there's a mod that might be conflicting, or maybe if you have a mod pack code, I could test it to see what's going on. Thanks!

**Comment by cmooref17** [comment]
I had another issue open about this, and I believe I got it sorted out in 2.1.22. Thanks for posting this!
