### ISSUE TITLE
Invisible player model when emoting v2.1.21

### ISSUE THREAD

**Issue by Enchanted-Games** [cmooref17/Lethal-Company-TooManyEmotes#138]
![image](https://github.com/user-attachments/assets/05b60d66-f36f-4695-95ff-8425c25317a4)

r2modman profile: 0190bc2e-6fe3-ea46-fc1d-f5ccbef7e902
happens in v2.1.21 with no other mods (apart from bepinex)

it only seems to happen to your own player model, other players appear fine while emoting

**Comment by cmooref17** [comment]
Thank you for the profile code! Let me check this out!

**Comment by cmooref17** [comment]
Oh, it's a modpack with only TME. Interesting. I was thinking it was a mod incompatibility.
I'll let you know what I find out.

**Comment by cmooref17** [comment]
Okay, I got the issue all sorted out. Apparently while I was testing this, another mod (Model Replacement API) was changing the layer that the player's body was rendering on, which I thought my mod was doing, so it looked fine.

This should be fixed on 2.1.22. Thank you!
