### ISSUE TITLE
[2.1.20 - 2.1.22] Employee Body invisible on Ship Camera Monitor

### ISSUE THREAD

**Issue by ZD-ChaofanJ** [cmooref17/Lethal-Company-TooManyEmotes#139]
The player's body is entirely invisible on the Ship Camera Monitor when using TooManyEmotes v2.1.20, v2.1.21, and v2.1.22 except for the legs, because apparently, Company Employees don't skip leg day.

This issue does not occur on TooManyEmotes v2.1.19.

Testing using only BepInEx and the TooManyEmotes mod.
Thunderstore Profile used for testing:  0190bdeb-fcf1-dc3e-fa4e-abe28764096a

To replicate the issue:

1. Use the profile code listed above or simply install the TooManyEmotes mod alone using r2modman or Thunderstore Mod Manager.
2.a. To see the issue, install TooManyEmotes v2.1.22
2.b To see the version without the issue, install TooManyEmotes v2.1.19
3. Run the game.
4. Open any save file.
5. Check the Ship's Camera Monitor.

![2 1 19](https://github.com/user-attachments/assets/2c0ec7b8-f75c-4c92-b4dc-e3d8b1144626)

![2 1 22](https://github.com/user-attachments/assets/77514a64-81c9-4e92-a30a-c8a3399c252e)

**Comment by cmooref17** [comment]
Is that camera from the vanilla game, or is it from a mod?
The vanilla camera seems to only be looking outside, unless I'm doing something wrong.

Thanks for bringing this up, though! I will look into this!

**Comment by cmooref17** [comment]
Nevermind, I think it was because I forgot to disable the Helmet_Cameras mod. Let me test this in a bit.

**Comment by cmooref17** [comment]
Okay, I think I have this fixed on 2.1.23. I believe I forgot to reapply my ship camera patch since I thought it wasn't needed anymore, but I was wrong.
Could you let me know if this works for you or not? And if so, feel free to close this issue!

**Comment by ZD-ChaofanJ** [comment]
Issue appears to be fixed as of v2.1.23 and later.
