### ISSUE TITLE
cannot open emotes wheel

### ISSUE THREAD

**Issue by matoof** [cmooref17/Lethal-Company-TooManyEmotes#142]
Hi I have some issues with the mod. 
Even if I uninstall and reinstall, change the version to an older one or change the keybind it's always the same end: the wheel don't want to appear. I have a 100% keyboard and I tried to change the key in my control AND in the LethalConfig menu. Did someone have an idea about my issue?

**Comment by cmooref17** [comment]
Have you noticed any errors in the console/log? I wonder if something caused an error and the keybind won't bind.
The error could be because of another mod, but it's hard to tell unless there were errors I could look it.

**Comment by matoof** [comment]
Hi, thanks to you I was able to make it work. At first logs at launch were good but when I was starting a game the key was entering in conflict with an other mod ! sorry for bothering you for something so simple and thx again

**Comment by cmooref17** [comment]
Oh, I see haha. Glad to hear it's working!
