### ISSUE TITLE
Emote "toosie slide" blocked on left click

### ISSUE THREAD

**Issue by Entreerex63** [cmooref17/Lethal-Company-TooManyEmotes#144]
Hello, 
my friend and I isntalled the mod and only for him, when he use is Left Click, the same emote "toosie slide" start.
He remove all this hotkeys, unistall all the game and thunderstore with the cache on AppData, and he's still emoting en left click...

Someone as a issue?

**Comment by cmooref17** [comment]
This happens when he left clicks? Is he not even in the emote menu when this happens?

**Comment by Entreerex63** [comment]
Hey, yeah exactly, but we figured out, it was the LethalEmotesAPI who cause that, but doesen't know why only on my friends...
