### ISSUE TITLE
cannot purchase emote due to TerminalTranslators

### ISSUE THREAD

**Issue by BottleOfErie** [cmooref17/Lethal-Company-TooManyEmotes#15]
I cannot confirm after ordered an emote in emote store.
After checked [this file](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/blob/main/TooManyEmotes/TerminalPatcher.cs),i found the string in line 34 was translated so it cannot be detected in line 146.
this issue can be solved easily by just remove TerminalTranslators.but i wonder if there is some other better solution?

sorry for my poor english.

how that string looks like on my pc:
![ODP6V TLS3I${R284AHUF2H](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/35907801/cedd3322-f895-4f2a-9cc7-608aae25673e)

**Comment by cmooref17** [comment]
Ah, I see what you mean. Let me try to get this fixed tomorrow. Thanks for letting me know!

**Comment by cmooref17** [comment]
Just wanted to update and check if you could test the new update for me. I'm hoping that I fixed this issue, but could you let me know?

**Comment by BottleOfErie** [comment]
it worked perfectly,thanks!
