### ISSUE TITLE
No View

### ISSUE THREAD

**Issue by pixo2000** [cmooref17/Lethal-Company-TooManyEmotes#152]
When i try to emote and move or just look arround, my mouse sometimesleaves the game?

**Comment by jurjen909** [comment]
I have had the same problem, in the current mod version (V2.2.0) when you select an Emote using the Emote Wheel. The Mouse/Cursor can leave the bounds of the Game and move onto another Monitor. This does not happen in normal Full screen, but does happen in Windowed Full screen.
I made a similar report on the LC Modding discord.
https://discord.com/channels/1168655651455639582/1184362437550555176/1275815330379206677

**Comment by cmooref17** [comment]
Oh shoot. I think I know what's going on. There was a line of code I forgot to revert while testing. Thanks for letting me know! I will get this fixed later today.
