### ISSUE TITLE
Emote Credits Not Saving

### ISSUE THREAD

**Issue by blastman67** [cmooref17/Lethal-Company-TooManyEmotes#154]
We have both PersistentUnlocks and PersistentEmoteCredits enabled but when someone leaves and rejoins their emote credits are set back to the default amount that we have set(0). They keep any purchased emotes but the credits seem to not save. tried looking through anything in the config that may help but had no luck

**Comment by cmooref17** [comment]
Thanks for this information. I'll check in a little bit, with your settings, and see if I can replicate this.

Do you have persistent global emotes enabled? (probably not the exact config name)

**Comment by cmooref17** [comment]
Also, maybe I should ask, do you guys have shared emote unlocks enabled, or not?

**Comment by blastman67** [comment]
we have both PersistentUnlocksGlobal & ShareEverything set to false

**Comment by blastman67** [comment]
I can send my entire config if that helps

**Comment by blastman67** [comment]
2 things I should also note is that the host's credits save like normal. And This also happens when it's the only mod enabled so it isn't a mod conflict issue

**Comment by cmooref17** [comment]
I think I found the issue, by the way. Thanks for posting the issue! I'll have it pushed out soon in another update

**Comment by blastman67** [comment]
alright. will let you know if it is fixed when the update comes out

**Comment by blastman67** [comment]
it's fixed yippee
