### ISSUE TITLE
Mod Not Working - Emote Wheel is not showing up

### ISSUE THREAD

**Issue by itzJoJax** [cmooref17/Lethal-Company-TooManyEmotes#16]
Downloaded the mod recently, wanted to test it out as it looked awesome, but when i got in game the emote wheel was not showing up. I tried working a bit with the settings using the LethalConfig mod but still nothing, i disabled any other mod to try and run it on its own but it still wasnt working so i have no clue.
I am getting an error in the terminal but i dont really know what i could do about it.

I dont know if the error has something to do with the mod not showing the emote wheel but here it is just in case

![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/65777136/77d207be-0b09-4d7b-9c30-8c8028f9dc7b)

**Comment by cmooref17** [comment]
Are you running on version v45 or later? They changed the method name for the scroll action. My first thought was that you're running v40 and that's why it can't see this method to patch.

**Comment by itzJoJax** [comment]
Oh damn, that makes total sense actually i am running on v40 thank you for making me notice that xD
