### ISSUE TITLE
Breaks character shadow

### ISSUE THREAD

**Issue by YoBii** [cmooref17/Lethal-Company-TooManyEmotes#2]
Hello thanks for your great mod,

I'd love to use it but unfortunately I find it breaks immersion because in first person my character's shadow is only a floating head/suit helmet. Screenshot attached. 

I tested this with game v45, bepinex 5.4.2200 and toomanyemotes 1.5.3. Only those installed on a new r2mm profile. 

![20231223140822_1](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/22051355/24cc66d3-1b2c-4a96-9e0b-412b2dd3ef30)

**Comment by YoBii** [comment]
Fixed with 1.5.4 ♥

**Comment by cmooref17** [comment]
Sorry, forgot this issue was also posted on here, otherwise I would have mentioned it was fixed!

**Comment by cmooref17** [comment]
Didn't mean to reopen.
