### ISSUE TITLE
Mirror mod compatibility

### ISSUE THREAD

**Issue by YuroKashine** [cmooref17/Lethal-Company-TooManyEmotes#22]
Good afternoon,

I have a request.
Please make this mod compatible with the mirror mod. the moment i do an emote i see myself in the mirror, the moment i go out of the emote my playermodel dissapears. it might also be because i have advanced company mod on AND more emotes mod. They somewhere between these 4 mods there seems to be an issue with the playermodel. i reckon its the toomanyemotes mod since i just added it and then it started to break.

**Comment by YuroKashine** [comment]
Also please make it compatible with the diversity mod... i noticed that i cant go blind anymore with this mod hahaha (blurry screen in gas)

**Comment by cmooref17** [comment]
I will try to re-look into the mirror mod issue. It worked at one point, but I'll have to check again.  Thanks for letting me know!

**Comment by cmooref17** [comment]
I forgot to post here, but I believe I fixed this in one of the more recent updates. If not, please let me know. Thanks!
