### ISSUE TITLE
Emotes  for Everyone

### ISSUE THREAD

**Issue by Ellysown** [cmooref17/Lethal-Company-TooManyEmotes#23]
Is there a option in the config where we could just unlock all the emotes without buying them? (**when I turned on party pooper, only the host unlocked the emotes**). and also if we disable it. it gets kind of annoying whenever we restart another server, we're gonna have type all of the emotes one by one again. TIA!

**Comment by afisarsy** [comment]
Host must Enable ```I am a Party Pooper``` and ```ShareEverything```

**Comment by cmooref17** [comment]
Emote "should" unlock for everyone if you have it set up that way in the config. It shouldn't be just the host.
Also, I did push an update that fixed some issues with non-host clients not loading emotes correctly. Could you let me know if this fixed your issue?

**Comment by Ellysown** [comment]
Hello enabling I am a Party Pooper and ShareEverything worked for me. thank you!
