### ISSUE TITLE
Since code restructuring (1.7.11) mod throws infinite errors with ModelReplacementAPI

### ISSUE THREAD

**Issue by NiranV** [cmooref17/Lethal-Company-TooManyEmotes#25]
I dropped back down to 1.7.10 and its not throwing any errors, even the latest 1.7.14 which improved compatibility is still throwing errors infinitely with ModelReplacementAPI mod loaded. Something something .getSafeEmote.

While both mods "seem" to work fine with each other despite throwing errors me and my friends did get some issues eventually with emotes unlocks no longer syncing and getting partially stuck (bend over back, arms back or to the side, stuff like that), though this might be something else entirely.

**Comment by cmooref17** [comment]
I will look into this. If you did get some useful logs, or errors, feel free to share them! I'm curious what's going on.

**Comment by cmooref17** [comment]
Okay, this should be fixed now. I forgot ModelReplacementAPI referenced one of my methods, and after I reorganized some code, it lost the reference. I added it back in, so it should be working fine with that mod again. (1.7.15)

**Comment by NiranV** [comment]
Thanks, i tested 1.7.15 and the errors are fixed.
