### ISSUE TITLE
Progress saving between saves

### ISSUE THREAD

**Issue by JakeHumphries4** [cmooref17/Lethal-Company-TooManyEmotes#26]
Not an issue, but I couldn't find an avenue to suggest this elsewhere. It would be nice if the purchased emotes were saved between sessions, so that you could collect them all, given the number of emotes and the rarity system. Other mods have implemented a similar system, such as advanced company, saving purchased perks over multiple runs.

Would you be entirely opposed to this? I think that it would make for a much more enjoyable experience in my opinion.

**Comment by cmooref17** [comment]
I believe I have fixed this in the latest update. Thanks for bringing this up!
