### ISSUE TITLE
Incompatible with mod 'Neofetch'

### ISSUE THREAD

**Issue by SirHazza** [cmooref17/Lethal-Company-TooManyEmotes#28]
Hello, when trying to add 'TooManyEmotes' to my modpack I found I was unable to access the terminal menu:

1. Entering keyword "emotes":
![entering emotes](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/31993698/808f6b4f-3247-402d-8972-2ff4099a66f6)

2. No emotes menu is returned:
![no emotes menu returned](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/31993698/ea6c0c96-da87-4d4a-adb6-18b02b6af030)

I narrowed down the conflict to be the mod [Neofetch](https://thunderstore.io/c/lethal-company/p/BeansDev/Neofetch/).

- Mods installed when testing for conflict:
![installed mod](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/31993698/4c962268-3428-47f9-a0c0-9e5af0c7d21a)

---

Please could you assess and potentially fix this conflict with Neofetch. As mentioned, I was attempting to add 'TooManyEmotes' to my modpack. And as shown below, Neofetch works perfectly with many other mods which interact with the terminal, 'TooManyEmotes' is the only mod I had an issue with.

- Other terminal mods I normally use in my modpack with Neofetch:
![neofetch works fine with many other terminal mods](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/31993698/fd1e9dcf-d826-455c-80a2-281c0e2c4891)

P.S. Thank you for your work on such top tier mods!

**Comment by cmooref17** [comment]
Let me see if I can reproduce this and see what the issue is. Thanks for letting me know!

**Comment by cmooref17** [comment]
I believe I got this issue fixed! I will be pushed in either 1.7.17, or 1.8, whichever update I end up releasing. Keep your eyes out for it!
