### ISSUE TITLE
Using emotes breaks spatial audio

### ISSUE THREAD

**Issue by SirHazza** [cmooref17/Lethal-Company-TooManyEmotes#29]
Hello, when using emotes with the 'TooManyEmotes' mod, spatial audio breaks. I've been able to recreate this issue a few times now.

Steps to recreate...

1. Create a new game
2. Land
3. Order from the store (i.e. a flashlight)
4. Stand next to the drop pod, with it directly to your left or right (makes detecting the issue easier)
5. Do a random assortment of using emotes, spinning the camera around, stopping and starting emotes by moving your character (Not exactly sure at which part the mod breaks)
6. The music from the dropship is no longer playing from the correct spatial position

I've also recreated this issue when I do step 5, but right at the start of the game on the ship, then land and spatial audio of the drop pod is already broken.

Tested in a fresh r2modman profile with TooManyEmotes v1.7.18 and BepInExPack v5.4.2100

P.S. Thank you for fixing my previous issue with Neofetch <3

**Comment by cmooref17** [comment]
Sorry for the late reply. I want to say I fixed this audio issue. If not, could you please create another issue? Thanks!
