### ISSUE TITLE
can't buy emote

### ISSUE THREAD

**Issue by tonito396pp** [cmooref17/Lethal-Company-TooManyEmotes#3]
![tải xuống](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/85762090/925f6463-958c-435a-837b-faa29eec326a)
why i can't buy emotes it say canceled order

**Comment by cmooref17** [comment]
Sorry for the late response, but it's possible you have the config set to only be able to purchase emotes with "emote credits". The default used to be that you could only do it that way, but I thought I changed it so the default would also let you use group credits.
