### ISSUE TITLE
Text Display is broken after update

### ISSUE THREAD

**Issue by ShadowWolf90** [cmooref17/Lethal-Company-TooManyEmotes#31]
Text in Radial Menu become invisible after recent update.

**Comment by ShadowWolf90** [comment]
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TMPro.MaterialReference..ctor (System.Int32 index, TMPro.TMP_FontAsset fontAsset, TMPro.TMP_SpriteAsset spriteAsset, UnityEngine.Material material, System.Single padding) (at <9baa8119dbcd498f902c1a92f10843c1>:0)
TMPro.TextMeshPro.SetArraySizes (TMPro.TMP_Text+UnicodeChar[] unicodeChars) (at <9baa8119dbcd498f902c1a92f10843c1>:0)
TMPro.TMP_Text.ParseInputText () (at <9baa8119dbcd498f902c1a92f10843c1>:0)
TMPro.TMP_Text.GetPreferredValues (System.Single width, System.Single height) (at <9baa8119dbcd498f902c1a92f10843c1>:0)
TMPro.TextMeshPro.Rebuild (UnityEngine.UI.CanvasUpdate update) (at <9baa8119dbcd498f902c1a92f10843c1>:0)
TMPro.TMP_UpdateManager.DoRebuilds () (at <9baa8119dbcd498f902c1a92f10843c1>:0)
UnityEngine.Canvas.SendWillRenderCanvases () (at <c6e732ee43764427b2b923952ecc7fa9>:0)
```

**Comment by cmooref17** [comment]
Thank you for this stack trace! Let me take a look.

**Comment by cmooref17** [comment]
Would there be any relevant logs before the one you shared? It doesn't actually help a ton, to be honest. There wasn't any type of error previous to this message?
Do you think there might have been another mod conflicting with this? Could be hard to guess though.

**Comment by ShadowWolf90** [comment]
Nope. No single error while loading and hosting, apparently maybe there was other mod that tried to load and caused TooManyEmotes to cause error later. MonitorLabels 1.3.0 caused this issue after little check and i reported that as well to creator.

**Comment by cmooref17** [comment]
Sorry for the late reply. It sounds like it's not a specific issue related to my mod. Would it be fine if I closed this since there's not much I can do?
