### ISSUE TITLE
Control Hint Uses Default Keybind

### ISSUE THREAD

**Issue by ChloeDawn** [cmooref17/Lethal-Company-TooManyEmotes#32]
The control hint for the emote radial menu on session start shows the default keybind and not the configured keybind.

**TooManyEmotes version:** 1.7.19

![20240117221916_1](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/9869940/09e15262-407b-40d7-affa-60bd8f0fc15e)

![20240117221801_1](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/9869940/b2336d46-5898-4298-ab98-0894b0e4172a)

**Comment by cmooref17** [comment]
Interesting. Let me see if this part hasn't been updated since I started supporting inpututils. I will check on this when I get home, thanks!

**Comment by cmooref17** [comment]
I'm going to remove this from the HUD for the next patch, but I will bring it back in the next one. The fix won't be hard, so it will return the next update!
