### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Soduem** [cmooref17/Lethal-Company-TooManyEmotes#33]
Where did you get the boogie down fbx? Having trouble finding it.

**Comment by cmooref17** [comment]
I believe it was from one of the fortnite packs from vrcmods. I couldn't tell you specifically where because it was awhile ago lol. I believe those ones would have been preconverted to fbx. Hope this helps!

**Comment by Soduem** [comment]
The ones you found do you remember if they're for Blender or Unity? Can't really find any of these in fbx form

**Comment by cmooref17** [comment]
Sorry for the late reply. I can check when I get home. If I can find the link I found them from, would you want that instead?

**Comment by Soduem** [comment]
That could work. Hope you still have the files.

**Comment by cmooref17** [comment]
This was where I got some of them. I know a lot of the animations were kinda broken, but hopefully this helps.
https://vrcmods.com/item?id=7474
