### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by dunholm** [cmooref17/Lethal-Company-TooManyEmotes#34]
i am trying to gain access to all of the emotes at the start however the config file isn't saving the value that allows all the emotes to be unlocked all at once at the start of the game. please help

**Comment by cmooref17** [comment]
The config file not saving sounds like an issue not related to my mod. Are you using a mod launcher to update the config, such as r2modman? And if so, when you edit the config, are you pressing the "save" button on the top to save the config?

If true to both, let me know and I can look into this.

**Comment by cmooref17** [comment]
Also, sorry for the late reply!

**Comment by dunholm** [comment]
no problem mate! at the time i was using BepinEX and was pressing save on the file. not sure whether it was bepin being the problem however i shall try this again.

**Comment by dunholm** [comment]
update : i have tried numerous times to get it to work however am not able to. in all honesty this is my first time trying to mod anything so have been relying upon youtube videos to help. i have been modding manually and i am not sure which files i need to drag where. all i have been doing is dragging the contents of the plugin file into the bepinex plugin file. are there any other files that need to dragged in? otherwise the boolean value on the unlock all emotes at the start keeps returning to false.

**Comment by cmooref17** [comment]
I'm not sure how specific the layout needs to be, but I believe how the mods are normally structured, are BepInEx/plugins/FlipMods.TooManyEmotes/TooManyEmotes.dll. The path to the configs is BepInEx/config/FlipMods.TooManyEmotes.cfg (obviously, this is just the example with my mod, but maybe structure it the same way?)

If using r2modman, you can just download the mods from the application, and they handle the rest for you.

**Comment by dunholm** [comment]
i've followed the sequence of where files are meant to go however the problem is still occurring. i opened the config file and set the value to true then saved it and upon launching and starting an online solo session then closing the game it seems like the boolean variable is getting reset to false when i check after.

**Comment by cmooref17** [comment]
Is this happening to every config entry? Have you tried setting other ones?

**Comment by dunholm** [comment]
i don't have any other mods installed however i can give it a try

**Comment by dunholm** [comment]
![image_2024-01-22_194451801](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/157069526/61bd9830-ebed-46b1-99a0-e72e6242edcf)

what line needs to be changed in order for it to work?

**Comment by dunholm** [comment]
update no. 2 : after having a mess around with another mod i have figured out that it is me playing a rookie error as it is my first time modding so i was changing the wrong thing in the file.
