### ISSUE TITLE
disappearing hands

### ISSUE THREAD

**Issue by funkyduckerino** [cmooref17/Lethal-Company-TooManyEmotes#36]
hi! i had an issue the past days with my hands disappearing ingame and holding items were disappearing as well, it seems that some emotes while dancing if i use the moreemotes mod pack for some reason it glitches and the hands and anything i hold disappear, only by rejoining it fixes. maybe you can fix this bug? thanks for the awesome mod and the time you give by updating it :)

**Comment by haroelim** [comment]
I am also having that issue, I could see my hands before emoting, but after using, for example, the "Laughing it up" emote, my hands disappear.

**Comment by cmooref17** [comment]
Were you both using MoreEmotes? I wonder if there's a weird issue going on with it. I'll try to look into this soon!

**Comment by haroelim** [comment]
Hello, I saw that this issue was closed, has it been resolved?

**Comment by funkyduckerino** [comment]
> Hello, I saw that this issue was closed, has it been resolved?

Good morning, I saw a rolling update came out with a fix with the moreemotes but I haven’t tried it out, I’ve removed the mod days ago so I’m not 100% sure it is still good
