### ISSUE TITLE
It does not allow you to turn the camera up and down

### ISSUE THREAD

**Issue by Paradox75831004** [cmooref17/Lethal-Company-TooManyEmotes#37]
It does not allow you to turn the camera up and down - only to the right and left.
Maybe something needed to be done somewhere in the config? I turned on the function so that I could run with emotion. Here is our build - 018d2aa9-aee1-0f1f-a848-3158e777950c
Is there any way to fix this?

**Comment by cmooref17** [comment]
I can look into this. I don't remember this issue when I was testing this, but it's possible. I will look into this later. Thanks for letting me know!

**Comment by cmooref17** [comment]
I believe I got this fixed. I will include it in the next update, which will hopefully be later tonight. Thanks for letting me know!
