### ISSUE TITLE
how do i stop an emote before it's supposed to end ?

### ISSUE THREAD

**Issue by jack652** [cmooref17/Lethal-Company-TooManyEmotes#39]
how do i stop an emote before it's supposed to end ?

**Comment by cmooref17** [comment]
You can cancel emotes by moving or jumping. If you allow moving while emoting in the config, you can cancel emotes by pressing escape. Or was this not quite what you meant?

**Comment by jack652** [comment]
> You can cancel emotes by moving or jumping. If you allow moving while emoting in the config, you can cancel emotes by pressing escape. Or was this not quite what you meant?

i tried both and none worked

**Comment by cmooref17** [comment]
Hmm, are you running any other emote mods by chance? Maybe better_emotes, or infinite emotes, that may be conflicting? And did you ever say if you were running the config that allows you to emote while moving?

**Comment by cmooref17** [comment]
I have recently updated the mod to 1.9.0 (1.9.1) and many things have changed, and should be much more stable. I can't say for sure that this part will have changed, but if you're still experiencing this issue, please reopen this issue!
