### ISSUE TITLE
Unable to buy emotes

### ISSUE THREAD

**Issue by zelll101096** [cmooref17/Lethal-Company-TooManyEmotes#41]
As the title states I'm having issues buying any emotes no matter what I type. I could just be dumb tho. Any help would be very much appreciated.

**Comment by cmooref17** [comment]
Are we opening up the emote store in the terminal by typing "emote" or "emotes"?
We should see a list of purchasable emotes.

If you do see them, you should be able to type the first word of the emote, or first few characters of the emote you want to purchase, and it should ask if you want to confirm the purchase.

If this doesn't help, which part isn't working for you?

**Comment by zelll101096** [comment]
So yes I saw the list of purchasable emotes. I think I found the issue tho. If you are at a fresh start (like a new save or you were just fired) the terminal acts like the emotes don't exist. It will say something like "there was no action with the words you typed". But once you land for the first time it works perfectly.

**Comment by cmooref17** [comment]
Hmm, it's not designed to be that way. I'm not 100% sure about if you're fired, but I feel like fresh starts should let you buy emotes, even if you haven't landed yet. I'll do some testing later.

**Comment by VanillaChan6571** [comment]
Can confirm that this is an issue, no matter what emote I typed it gives the result back of: "there was no action with the words you typed"

**Comment by cmooref17** [comment]
Are you guys running any mods that might conflict, such as any mods that affect the terminals? Maybe translation mods? I've had a translation mod in the past cause issues before, so I'm just curious.

And if possible, would it be easy to send me a quick video of this issue?

**Comment by VanillaChan6571** [comment]
> Are you guys running any mods that might conflict, such as any mods that affect the terminals? Maybe translation mods? I've had a translation mod in the past cause issues before, so I'm just curious.
> 
> And if possible, would it be easy to send me a quick video of this issue?


https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/39040261/e4f51143-addd-489a-9000-67f517d54242

Video looks bad due to Github 10mb limit.

**Comment by cmooref17** [comment]
By the way, which mod adds that text, or those question marks, to the top left of the terminal, just in case it's conflicting. Also, let me try testing a few things. Thanks for the video!

**Comment by cmooref17** [comment]
Okay, I think I found the issue. It seems like for whatever reason, I don't handle character "case" correctly, such as capital letters and such. Let me get a fix for this out soon. Thanks so much!

**Comment by VanillaChan6571** [comment]
> By the way, which mod adds that text, or those question marks, to the top left of the terminal, just in case it's conflicting. Also, let me try testing a few things. Thanks for the video!

[Terminal Clock](https://thunderstore.io/c/lethal-company/p/NotAtomicBomb/Terminal_Clock/)

**Comment by cmooref17** [comment]
By the way, late response, but I believe this issue should be fixed in a recent update. Thanks for letting me know about this! If it's not fixed, please reopen this issue!
