### ISSUE TITLE
Getting emotes

### ISSUE THREAD

**Issue by Ann1x** [cmooref17/Lethal-Company-TooManyEmotes#43]
Hello! I want to get all emotes without buying each of them and heard that I need to find "I am a party pooper" and change **false** to **true**. When I do this I still have only 8 emotes. Can you please tell me what should I do?

**Comment by cmooref17** [comment]
That doesn't seem right. After you check that you only have 8 emotes, if you closed the game and checked your config, is the party pooper config still set to true? I personally haven't seen this not work for me.

**Comment by cmooref17** [comment]
Could you let me know if this is still an issue for you? I didn't make any specific fix for this since it seems like it should be working, but I just wanted to double check. Thanks!

**Comment by cmooref17** [comment]
I'm not sure where the winrar one came from, but you probably don't need to touch that. How do you install your mods? Do you use a mod manager, or do you manually place your mods in a plugins folder somewhere?

And would you be able to give me a path to the TooManyEmotes config file, in relation to the BepInEx folder? I think it should be BepInEx/config/FlipMods-TooManyEmotes.cfg (or maybe it's just named TooManyEmotes.cfg)

**Comment by Ann1x** [comment]
I'm actually so stupid. I thought I need to change it in ConfigSettings.cs... Thank you so much! Now I have all emotes

**Comment by cmooref17** [comment]
Ahhh, that would do it, and no problem!
