### ISSUE TITLE
BetterEmotes update

### ISSUE THREAD

**Issue by KlutzyBubbles** [cmooref17/Lethal-Company-TooManyEmotes#44]
I didn't realize this mod had a compatibility check for my mod, and the most recent update changed the path of the
EmotePatch

changing https://github.com/cmooref17/Lethal-Company-TooManyEmotes/blob/ed03e6433614e8f66d4978d8a2b0634c748d7082/TooManyEmotes/CompatibilityPatcher.cs#L88

to 

`Type internalClassType = assembly.GetType("BetterEmote.Patches.EmotePatch");`

Should fix it, nothing else related to the patch has really changed.

**Comment by cmooref17** [comment]
Ah yes, I can get this changed in the next update. Thanks!
