### ISSUE TITLE
Bug with hands

### ISSUE THREAD

**Issue by Avessalomoff** [cmooref17/Lethal-Company-TooManyEmotes#51]
Hands go inside player body when use emotes from your mod after using twerk from More Emotes (idk why it happens only with twerk lmao). 
On screenshot you can see the therminal from Advanced Company inside the body
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/116974784/5e79bdff-19d2-4bbc-b4ba-caad22dfdbf7)

**Comment by cmooref17** [comment]
Does this happen when you perform an emote while you're currently in the twerk animation? It seems like this may be a conflict in general, and has been for a bit. I'll see if I could put more protections in place to prevent this on my side. Hopefully!

**Comment by Avessalomoff** [comment]
no, this happen only when you stop twerk animation and then use dances

**Comment by cmooref17** [comment]
Oh, interesting. I'll look into this when I get the chance. Thanks for posting this issue!

**Comment by DrFeederino** [comment]
I found the repo just now. Do the twerking from MoreEmotes and then switch to the any other emotes from wheel menu ("~" button), then performing any default emotes will show no hands and hands disappear.

**Comment by cmooref17** [comment]
I have just updated the mod, and it's not on 1.9.1. A lot of the framework has changed, and I don't touch the original player's animator component anymore. If this still happens, it's probably something that that mod is doing. Let me know if it's still happening!

**Comment by Avessalomoff** [comment]
Good news, it fixed!
