### ISSUE TITLE
Suggestion: implementation of the model reloading

### ISSUE THREAD

**Issue by Multiname** [cmooref17/Lethal-Company-TooManyEmotes#52]
I play with FreeCammer v1.2.4 and when I enter the free camera mode, my model becomes invisible:

![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/36795381/d8d6eeda-7119-4154-9bf4-99ae58235eda)
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/36795381/0ea6d5a7-36cb-4b00-8744-b386fa19cd79)

To fix it I need to restart the save, which is problematic if I'm the host. So I just want to ask, could you add some button that will reload my model?

**Comment by cmooref17** [comment]
Does enabling the free camera cause the model to go invisible? Not when you emote, correct? I could probably add this in the next patch. I don't want to add a default keybind for this, though, so I might only allow setting the keybind with InputUtils installed if that works for you.

**Comment by Multiname** [comment]
Oh no, is there any way to avoid InputUtils? It breaks some of my mods...

**Comment by Multiname** [comment]
And yeah, it doesn't matter where to enter the free camera mode

**Comment by Multiname** [comment]
I've tested the new update and realized that reloading the model doesn't help, so I think I should give an appropriate list of steps to recreate the problem:
- Create new profile
- Get TooManyEmotes v1.8.6 and FreeCammer v1.2.4
- Start new game
- Enter the free camera mode
- Emote

**Comment by cmooref17** [comment]
Okay thanks! Let me see if I can find anything out!

**Comment by Multiname** [comment]
Hey, I rewatched my replays and noticed that previous versions of my mods didn't have this problem yet. I've tested it and found out that the problem occurs if FreeCammer has version 1.2.4. So if it can help with investigations, FreeCammer v1.2.3 doesn't cause the problem.

**Comment by Multiname** [comment]
I have good news, the FreeCammer developer fixed the issue on his side, so there is no problem anymore.
