### ISSUE TITLE
Animation and Sound Bug

### ISSUE THREAD

**Issue by WarMaster2207** [cmooref17/Lethal-Company-TooManyEmotes#53]
The mod works fine, but when you land on a moon, the default sound and animation for walking stops working, so your just sliding around and it's the same when you go back to orbit

**Comment by cmooref17** [comment]
Sorry for the late reply. Has this been a consistent issue? And does this happen every time for you?

**Comment by WarMaster2207** [comment]
Yeah, it works fine when I enter the game, but once I land the animations stop working, just the emotes are animated, but it work fine on 1.8.5w

**Comment by cmooref17** [comment]
I updated the mod, and changed a bit of the framework. I can't say for sure this has been fixed, but could you let me know? If it's still happening, I will look into this again.

**Comment by WarMaster2207** [comment]
Yep, I can confirm that it's fixed, thanks  !  : )
