### ISSUE TITLE
Animation Bug

### ISSUE THREAD

**Issue by nicopiov** [cmooref17/Lethal-Company-TooManyEmotes#55]
### After Update 1.8.6, we're having this bug in every game

We create the lobby and select the moon (everything is fine till there)

As we start the game our characters are stuck in a standing still animation:

- The characters just slide onto the terrain
- If we try to crouch, the game logic recognize that we're crouching (lower movement speed and can pass under things) but the first person pov is like as we're standing up
- whenever you pick up an item or you have an item in your hands, you're not able to see it. Even with bigger items, you just get the text "hands full"
- whenever you try to enter the terminal the pov is like far away from the terminal screen, making it difficult to read. And not close like default when the character lean towards the screen

I tried to be as accurate as possible when describing the issue. Hope it helps!

**Comment by cmooref17** [comment]
Sorry for the delay. I'm performing a code restructure, which will change how emotes are handled. This should fix many bugs, and maybe this one included, so maybe we can check to see if this issue is still there after I push the update, hopefully this weekend.

**Comment by nicopiov** [comment]
Don't worry, i just saw the reply. Anyway as you'll push the update i'll let you know if is everything good. Thanks mate!

**Comment by cmooref17** [comment]
I have updated the mod now, and it's currently on 1.9.1. Hopefully everything will be fine with your issue, but please let me know!

**Comment by nicopiov** [comment]
Ok sorry for the delayed reply. I just tested out the 1.9.3 version and everything seems working fine. Thanks for the update! ^^
