### ISSUE TITLE
Cosmetics Don't Appear In Third Person When Advanced Companies Installed

### ISSUE THREAD

**Issue by PolyframeX** [cmooref17/Lethal-Company-TooManyEmotes#56]
Not sure why, but for some reason when emoting and having Advanced Company installed, all of the cosmetics applied just, don't appear. I am on the latest version for everything.

Emoting works fine, and with Advanced Company the Custom Clothing works fine, so I'm not sure what the issue is.
If you want to test it for yourself, you can with the modpack code: 018d848a-a591-7341-13ea-d45923ead578

**Comment by cmooref17** [comment]
Interesting. I will check this out sometime when I got some free time.
