### ISSUE TITLE
The Rick Dance = The Company Building

### ISSUE THREAD

**Issue by MushiShirohime** [cmooref17/Lethal-Company-TooManyEmotes#57]
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/38385343/f0137bcf-15f5-4c48-bd06-7a259e1677ac)

**Comment by cmooref17** [comment]
Is this on the latest version of this mod?

**Comment by cmooref17** [comment]
I actually think I found the issue to this. I will have this fixed in the next update. Thanks so much!
