### ISSUE TITLE
[Request] Option to remove "complementary" emotes from "common" tier

### ISSUE THREAD

**Issue by ajsglist** [cmooref17/Lethal-Company-TooManyEmotes#58]
Howdy, just finished setting up TME 1.9.0, and so far things are looking good!  I noticed the complementary emotes have expanded considerably (14 now).  Would it be possible to get a config option to remove them from the "common" tier, so that only user-bought emotes would populate there?

Thanks

![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/139426529/f36df713-11ea-4746-b889-6de67e46200c)

**Comment by cmooref17** [comment]
Thanks for the suggestion! Actually, this makes sense, and not sure why I hadn't done this already. I just added this in update 1.9.1!
