### ISSUE TITLE
MissingMethodException: Method not found: TooManyEmotes.UnlockableEmote...

### ISSUE THREAD

**Issue by VanillaChan6571** [cmooref17/Lethal-Company-TooManyEmotes#60]
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/39040261/f2c747e8-2c94-4b67-962a-05f836e290ca)

[Error  : Unity Log] MissingMethodException: Method not found: TooManyEmotes.UnlockableEmote TooManyEmotes.Patches.PlayerPatcher.GetCurrentlyPlayingEmote(GameNetcodeStuff.PlayerControllerB)
Stack trace:
ModelReplacement.BodyReplacementBase.SafeGetEmoteID (System.Int32 currentID) (at <04ead122e9454c3ab64b59c6b8a378e3>:IL_0001)
ModelReplacement.BodyReplacementBase.Update () (at <04ead122e9454c3ab64b59c6b8a378e3>:IL_01B1)

Spams console.

**Comment by VanillaChan6571** [comment]
> ![image](https://private-user-images.githubusercontent.com/117127021/304302721-71449b43-e243-4b12-b23d-7082db9ebd9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDI3NDEsIm5iZiI6MTcwNzgwMjQ0MSwicGF0aCI6Ii8xMTcxMjcwMjEvMzA0MzAyNzIxLTcxNDQ5YjQzLWUyNDMtNGIxMi1iMjNkLTcwODJkYjllYmQ5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwNTM0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODdkMDFiMDY0YWNhZTYwYzcyMzA5YzZhNDlkOTllYThjNDI0NDNmNmU3ODJiNGVjZmNhOTVjYTA5YzE5YmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MB-OC0wgs07yetMH9Vnqni_ZiaCabCmd8KCS9CaPRBs)
> 
> :P

Not using LCVR or MRAPI

x2 :P

**Comment by ZhuJap** [comment]
+1

**Comment by cmooref17** [comment]
Sorry about this! A hot fix will be incoming soon!

**Comment by cmooref17** [comment]
I pushed the hotfix update, and this should be fixed again (hopefully). Please create another issue if it still appears, thanks!
