### ISSUE TITLE
[Bug] With update 1.9.0, mod doesn't allow to scroll through items.

### ISSUE THREAD

**Issue by Uniteria** [cmooref17/Lethal-Company-TooManyEmotes#62]
Hey :) As tittle said, mod doesn't allow to scroll up and down which broke switching between items. I dont know if it's only me with my mods, or this issue is common. If it's only me, then i will post all mods / logs. Thanks ^^

**Comment by metelkoww** [comment]
we have the same problems, but when we reinstall to 1.8.6 scroll is working again

**Comment by Uniteria** [comment]
> we have the same problems, but when we reinstall to 1.8.6 scroll is working again

Same :) I've reverted back to 1.8.6 and all seems gucci.

**Comment by TheNasbit** [comment]
Scrolling on Terminal works neither. Probably related.

**Comment by cmooref17** [comment]
Sorry all! This has been fixed, and the update has been pushed. Thanks for letting me know! Update should be 1.9.1
