### ISSUE TITLE
LCVR Compatibility check is overly strict

### ISSUE THREAD

**Issue by DaXcess** [cmooref17/Lethal-Company-TooManyEmotes#65]
The `LCVR_Patcher.Enabled` property only checks for the existence of the VR mod, but not actually whether the game was launched in VR or not. This causes the combination of LCVR + TooManyEmotes to completely disable TooManyEmotes, even though flatscreen players with the VR mod should be able to perform emotes.

The way that BetterEmotes tackled this was checking the flags set by LCVR, though this requires an assembly reference to LCVR, which then gives you the ability to check if the game is in VR by checking `LCVR.Plugin.Flags.HasFlag(Flags.VR)`.

**Comment by cmooref17** [comment]
Thanks for letting me know! That was a whoopsie on my part. I forgot to check that, but it has been fixed, and will be pushed out in the update later today.
