### ISSUE TITLE
Corporate Restructure Mod Breaks TooManyEmotes

### ISSUE THREAD

**Issue by Grizzek98** [cmooref17/Lethal-Company-TooManyEmotes#66]
Not super familiar with modding, but I checked my mods one by one until I determined that TooManyEmotes breaks when Corporate Restructure is enabled. Specifically, when you load into a game and try to emote, third person will not activate but I think the emote still happens. Anytime you emote after the first time, the third person camera will activate, but will be stuck outside looking at the side of the ship. If you land the ship and emote, the camera will be stuck on the moon looking at where the side of the side would be landed (even when the ship is still moving down).

**Comment by ajsglist** [comment]
Mirroring the comment I made to someone else having CorporateRestructure issues (CR is buggy and takes other mods with it when it throws NREs)

https://github.com/cmooref17/Lethal-Company-TooManyEmotes/issues/71

**Comment by 21Sumter** [comment]
Openmonitor is a refork of that fashion, there are no problems with it

**Comment by 21Sumter** [comment]
OpenMonitors is a refork of that fashion, there are no problems with it

**Comment by cmooref17** [comment]
Also, I can't remember everywhere where I have mentioned this, but it looks like it was not mentioned here, but yes, as mentioned, corporate restructure does throw an error which prevents The games spawn animation method from running, and this blocks some of my code related to my emote camera. For those who would like to use corporate restructure still, I have a temporary patch that will get around this issue, but it will be included in 1.9.4.

**Comment by 21Sumter** [comment]
> Also, I can't remember everywhere where I have mentioned this, but it looks like it was not mentioned here, but yes, as mentioned, corporate restructure does throw an error which prevents The games spawn animation method from running, and this blocks some of my code related to my emote camera. For those who would like to use corporate restructure still, I have a temporary patch that will get around this issue, but it will be included in 1.9.4.

![IMG_2482](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/123876668/b4dac90e-511e-4e5d-87f2-afc9afdae87b)
