### ISSUE TITLE
V1.9.2 broken emote 

### ISSUE THREAD

**Issue by PxTame** [cmooref17/Lethal-Company-TooManyEmotes#68]
Hello i would love to report an issues, after updating TooManyEmotes from the V1.8.6 to the V1.9.2 every emote seem to be broken and only display the default animation

After some test, i've figured out that TooManyEmotes and LethalVRM didn't work together after the V1.8.6
When i'm looking at the console on V1.9.2, nothing weird appear while playing the emote
Is there any way we can keep the mod update and fixing this issues?

Thanks

**Comment by 21Sumter** [comment]
use version 1.9.1

**Comment by cmooref17** [comment]
Sorry about this. I apparently mixed some of my testing files into the update and didn't realize it. It should be good again on 1.9.3.
