### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by trifolyate** [cmooref17/Lethal-Company-TooManyEmotes#7]
I am using this profile in Thunderstore: 018ce26d-c626-708b-8932-3176f2ce19fb

Whenever I do an emote, this happens.

![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/104475731/e41491c9-64d0-494f-8145-72ba89a07faa)

Seems like the arms are not done correctly

**Comment by cmooref17** [comment]
Hmm, are you using any mods that might be conflicting? Or have you noticed any relevant errors in the console?
