### ISSUE TITLE
seeing side of ship

### ISSUE THREAD

**Issue by cupovbees** [cmooref17/Lethal-Company-TooManyEmotes#70]
i have a problem where i try to use any emote and it shows the side of the ship no matter where i am, i do sometimes have the problem is the dance 1 instead of the new emotes. i removed all emote mods just incase that was it and nothing has changed.

**Comment by cmooref17** [comment]
The default dance emote was a bug in 1.9.2 because I accidentally mixed up some testing files into the update. Should be fixed in 1.9.3.

The side of ship bug seems to be a bug that is caused by the corporate restructure mod for whatever reason. Do you by chance have this mod installed?

**Comment by cupovbees** [comment]
ahh thank you, and i do have that mod, i disabled it and was able to use it fine now. i also updated o both problems are sorted now
