### ISSUE TITLE
incompatibility with Corporate Restructure

### ISSUE THREAD

**Issue by 21Sumter** [cmooref17/Lethal-Company-TooManyEmotes#71]
I played on version 1.9.1, and discovered an incompatibility with the mod, yesterday after adding the Corporate Restructure mod, this mod breaks the emotions camera, or rather, the camera is static and it is located behind the ship, I did not test emotions inside locations (buildings) and did not conduct other tests, since I immediately disabled the mod, I think it’s causing problems, but I still ask you to consider the opposite option, I didn’t find how to contact the author of that mod, so I’m telling you about it

**Comment by ajsglist** [comment]
corporate restructure frequently throws and NRE that takes other mods with it.  The CR dev was notified a long time ago but has never responded.  I'd recommend checking out other mods with the same functionality to see if it resolves the issue.

**Comment by 21Sumter** [comment]
OpenMonitors is a refork of that fashion, there are no problems with it. Closed

**Comment by 21Sumter** [comment]
OpenMonitors is a refork of that fashion, there are no problems with it. Closed
