### ISSUE TITLE
What's the reference name of the emotion?

### ISSUE THREAD

**Issue by VinceHov** [cmooref17/Lethal-Company-TooManyEmotes#72]
There's no "question" section, so i decided to write this question here.

In your mod i found "Error" emotion that looks like old youtube video where anime/real girl jumps in the air.
If anyone knows what the name of the video (or song that used in this video), please, tell me.

**Comment by cmooref17** [comment]
Sorry for the super late reply, but this emote has been renamed to "Get down", which I believe is the name of the song that the character dances to in beatsaber. Hopefully this helps!

**Comment by VinceHov** [comment]
Yes, it's this song. Thanks a lot!
