### ISSUE TITLE
Inconsistent keybind interface

### ISSUE THREAD

**Issue by dannycreations** [cmooref17/Lethal-Company-TooManyEmotes#73]
FlipMods-TooManyEmotes-1.9.3

## Problem 1
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/44817214/0a33995c-3b6e-4ec8-85b9-a33af4e870ec)
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/44817214/77e471ab-4c51-4589-9c49-322aa456b245)

## Problem 2
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/44817214/fd0475c7-6f09-4c91-ae16-c95c3db95065)
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/44817214/86802a39-f7fd-469e-a2f0-a4d1f87db7bc)

**Comment by cmooref17** [comment]
Sorry Dan, just getting to this. In the first screenshot, does this happen after you set the keybind? Does it ever display c? Or has it after restarting?

The second one should be fixed in the next update. Hopefully will push it out soon

**Comment by dannycreations** [comment]
> Sorry Dan, just getting to this. In the first screenshot, does this happen after you set the keybind? Does it ever display c? Or has it after restarting?
> 
> The second one should be fixed in the next update. Hopefully will push it out soon

in my case, it never changed to C, either setting the keybind using ingame settings (InputUtils) or changing it manually in the config (.cfg not .json) or fully restart game

**Comment by cmooref17** [comment]
In 2.0.0, I believe I fixed most (hopefully all) issues related to keybinds and their display names.

**Comment by cmooref17** [comment]
I thought I fixed this. I'll check, but if not, it will be included in the next patch.
