### ISSUE TITLE
[Request? Bug?] scrap no longer animates with emotes

### ISSUE THREAD

**Issue by ajsglist** [cmooref17/Lethal-Company-TooManyEmotes#74]
Not sure if this is a bug with the new 1.9.0+ TME emote rigging or if its intended behavior, so not sure how to flag it (sorry).

Prior to the rigging update, scrap would animate along with the emoting player (e.g. held scrap would get waved around in the air when the player waves their arms around).  This was amazing, and our group loved it.  1.9.0+ appear to have the held scrap float statically in front of the emoting player.  It's quite jarring.

Is it possible to restore this functionality to work with the new emote system?  Even if only as an opt-in config option

Thanks for the consideration

**Comment by cmooref17** [comment]
Well, I will say it wasn't intentionally removed. Let me check out why this is happening, and hopefully I can fix it. Thanks for letting me know!

**Comment by ajsglist** [comment]
Hey there, this issue is still present up through 2.0.0.  We've been using 1.8.6 this whole time, since every subsequent version does not animate scrap.
![TME_2 0 0_still_doesnt_animate_scrap_crop](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/139426529/9c0cc698-41d3-4d43-a56e-e9abf978fb6d)

**Comment by cmooref17** [comment]
Yes sorry, I forgot about this issue. I will be going to bed soon, but hopefully I can post a hotfix tomorrow and include this.
