### ISSUE TITLE
Missing emotes

### ISSUE THREAD

**Issue by fail5xsuccess** [cmooref17/Lethal-Company-TooManyEmotes#77]
Didn't see anything in changelogs about removal of specific emotes, but the "Flipping" emotes seem to have disappeared. Flipping Sexy was one of them, can't remember the name of the other.

**Comment by DenisMrCreeper** [comment]
I notice that too! Also California Gurls disappeared again ;c

**Comment by cmooref17** [comment]
This is so strange. I don't even feel like I touched the list of emotes last update. There's some supernatural stuff going on lol. Let me check on these when I get home
