### ISSUE TITLE
When using a controller to start an emotes nothing happen

### ISSUE THREAD

**Issue by RedSun42** [cmooref17/Lethal-Company-TooManyEmotes#79]
Hello Been testing controller support for Too many emotes and it seem like nothing happen when using the Wheel with a controller I tried with Input utility and same issue. If you first use keyboard and mouse to use the wheel after that all emotes used using controller play the default dance emotes in first person 

Rolled back to 1.8.6 and it work so something happen in a recent update

Cheers

**Comment by cmooref17** [comment]
Hmm, I'll have to test this when I get home, but thanks for bringing this up!

**Comment by cmooref17** [comment]
Sorry for the delay, this has been fixed, and will be pushed soon in 2.0.3

**Comment by RedSun42** [comment]
Awesome :) thanks!
