### ISSUE TITLE
Camera for non-host clips outside/to the ship regardless if on planet or not

### ISSUE THREAD

**Issue by YnwLNE** [cmooref17/Lethal-Company-TooManyEmotes#8]
Works for anyone that is the host without issues but anyone who joins will have their camera snapped to the left side outside the ship until the animation ends.

**Comment by cmooref17** [comment]
Interesting. And they can't turn their camera or anything?
Would there be any possible mod conflicts?
If possible, I'd love to get a video of this. I have not seen this happen before :/

**Comment by henrikaag** [comment]
I got the same issue, as a host. Haven't tried with others yet.
Video from outside the ship: https://streamable.com/6iueek
If you do it inside the ship it will just snap the camera outside it as stated in the first report.

**Comment by DannyBoyXD** [comment]
I also have the same problem. I've extensively checked all my mods one by one and the conflict happens with corporate restructure mod. Not sure if theres other mods that will have the same issue but I got a pretty decient size mod list of the most popular ones and this mod is causing conflicts.

**Comment by cmooref17** [comment]
I have heard this about corporate restructure. Maybe I can look at their code and see what's causing it, and maybe it'd be an easy fix for me? Otherwise, we might just have to wait for them to fix it themself.

**Comment by DannyBoyXD** [comment]
Yeah im not sure how to contact the devs but I bet you its something to do with the last change that they made that states: "Removed Host Eject due to v47"
