### ISSUE TITLE
Issue with the favorites menu

### ISSUE THREAD

**Issue by AJWRDiamonds** [cmooref17/Lethal-Company-TooManyEmotes#85]
when favoriting the jug band emote it doesnt appear in the favorites menu. i originally thought i was just missing it but after i added another emote for a new favorites page and tried re-adding it it wasnt appearing. i then noticed it wasnt increasing the favorites value.

**Comment by cmooref17** [comment]
Yes, I have heard this, but I will be looking into this soon. Should be a simple fix!

**Comment by cmooref17** [comment]
You should be able to favorite it in the latest update!
