### ISSUE TITLE
bug between toomanyemotes and reserved slot

### ISSUE THREAD

**Issue by Akakaryu** [cmooref17/Lethal-Company-TooManyEmotes#86]
hello,

since the update, i can't acces to the emote shop,
when i try, it take me to the reserved item slots shop,
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/163343748/15c1973c-8c45-46d6-8d05-96b2b8099fd3)
![image](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/163343748/8e1e3661-062e-4931-81da-0755f6ec3040)
i try with a friend and the same thing happen.

is there a way to fix it ?

Thanks you in advance for your answer, and have a nice day !

**Comment by Akakaryu** [comment]
by update, i mean the reserved item slot update (2.0+) i rolled back to older version of the mod for now

**Comment by cmooref17** [comment]
Oh shoot, I have made a mistake in my terminal patcher that conflicts. Whoops! I will get this fixed when I get home. Thanks so much!

**Comment by Akakaryu** [comment]
you're welcome

**Comment by cmooref17** [comment]
I was actually finishing up a few bug fixes, so I decided to just fix it real quick and push out the update before I went home. It should be fixed in 2.0.3, as well as some other fixes for unrelated items.
