### ISSUE TITLE
Double/Big head

### ISSUE THREAD

**Issue by Mayple7** [cmooref17/Lethal-Company-TooManyEmotes#97]
Watching someone else do an emote produces this effect where it looks like a second head that is extra large is overlaid on top: 
![2024-03-23 19_42_19-Lethal Company](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/5624333/e62fb8e2-43bb-4626-bffd-3aa6571e1ac6)

We tried disabling all mods except this one and the big head effect persists. If we sync emotes or play a different emote the big heads disappear and it looks normal again.

**Comment by RatserX** [comment]
Can confirm this is happening on the latest version.

**Comment by cmooref17** [comment]
Oh shoot, that wasn't supposed to be there. Let me get that fixed, thanks!

**Comment by cmooref17** [comment]
Btw, I did push another update. Let me know if this doesn't fix it. I didn't actually test it since I don't have someone to test with atm, but I definitely saw the problem.

**Comment by Mayple7** [comment]
Seems like the big head issue is fixed but I'm seeing my More Company cosmetics being copied over to others when I start emoting:
![2024-03-23 22_28_46-Lethal Company](https://github.com/cmooref17/Lethal-Company-TooManyEmotes/assets/5624333/8cd7c177-2c4b-4e4c-ab92-0c68912d9dda)

Thanks for the quick turnaround!

**Comment by cmooref17** [comment]
I haven't seen this happen in a while. I'm not sure what would have changed, but I might have to test this myself.

**Comment by cmooref17** [comment]
I'm not great at checking the github, but I believe this should be fixed. If not, please recreate the issue, thanks!
