### ISSUE TITLE
Reconnecting Players Playing Jug Band

### ISSUE THREAD

**Issue by ChloeDawn** [cmooref17/Lethal-Company-TooManyEmotes#98]
Sometimes when a player reconnects to a lobby utilizing LateCompany or LobbyControl, they will join with Jug Band audio emitting from them for some if not all other players on the ship (but not themselves), and will have to trigger and cancel the Jug Bang emote to silence it. I think this only happens if they had used Jug Band at some point before disconnecting but I'm not sure. This may be unrelated to LateCompany or LobbyControl as it may be possible to reproduce in the initial pre-game lobby (unsure) but I felt it was relevant to include them as I have personally only experienced the bug with each present previously.

**Comment by cmooref17** [comment]
I've had a similar issue with a friend, but it was with them using the saxophone emote. Both of those emotes play from the player, and I have gotten reports of audio doing similar things when players enable the option to emote from the player with all emotes (disabling the boombox) so maybe there's an issue with. I will look into this soon. Thanks!

**Comment by cmooref17** [comment]
So I'm currently looking for a way to replicate this easily. Would you happen to have steps that I could follow to force this error to occur? I'm asking others as well that ran into this issue. Thanks!

**Comment by cmooref17** [comment]
I will close this issue for now since I have since pushed a patch to hopefully fix this, but if this is still happening, please recreate this issue.
